VER="3.1_u2h_04-08_10w_lr2_noweight_1ratio_correctw_0.2defaultp_250epoch_1skip_save180200_T1Only_prev_3Dec"
SOURCE="ucf101_flow_test_split_1"
TARGET="hmdb51_flow_test_split_1"
SOURCE2="ucf101_rgb_test_split_1"
TARGET2="hmdb51_rgb_test_split_1"
MODE="Flow"
MODE2="RGB"
FW=0.4
MW=-0.8
LR=0.002
LR2=0.001
WT=1
BATCH=36
EPOCHS=250
PRERATIO=0.2
FLOWPREF="flow_"
FLOWPREF2="flow_"
PSR=1
DD="False"
TD="True"
USEPREV="True"
DEFP=0.2
SKIP=1
MP=0.5
UT1="True"
nohup python main_cospcan_ratio_2Dec_prev_save.py hmdb51-10 $MODE $MODE2 datalist/$SOURCE.txt datalist/$TARGET.txt datalist/$SOURCE2.txt datalist/$TARGET2.txt --usingTriDec $TD --max_pseudo $MP --useT1Only $UT1 --arch BNInception --skip $SKIP --usePrevAcc $USEPREV --defaultPseudoRatio $DEFP --pseudo_ratio $PSR --usingDoubleDecrease $DD --num_segments 3 --gd 20 --lr $LR --lr2 $LR2  --lr_steps 180 230 --pre_ratio $PRERATIO --epochs $EPOCHS -b $BATCH -j 8 --dropout 0.7 --dropout2 0.8 --snapshot_pref $VER --form_w $FW --main_w $MW --wt $WT --flow_pref $FLOWPREF --flow_pref2 $FLOWPREF > $VER.txt &
# VER="3.2_u2h_04-08_10w_lr2_noweight_0.5ratio_correctw_0.2defaultp_250epoch_1skip_save180200_T1Only_prev_3Dec"
# SOURCE="ucf101_flow_test_split_1"
# TARGET="hmdb51_flow_test_split_1"
# MODE="Flow"
# SMODE="flow"
# FW=0.4
# MW=-0.8
# LR=0.002
# GPU=1
# WT=1
# BATCH=48
# EPOCHS=250
# PRERATIO=0.2
# FLOWPREF="flow_"
# PSR=0.5
# DD="True"
# TD="True"
# USEPREV="True"
# DEFP=0.2
# SKIP=1
# MP=0.5
# UT1="True"
# echo "${VER}_${SMODE}"
# nohup python main_spcan_ratio_2Dec_prev_save.py hmdb51-10 $MODE datalist/$SOURCE.txt datalist/$TARGET.txt --usingTriDec $TD --max_pseudo $MP --useT1Only $UT1 --arch BNInception --skip $SKIP --usePrevAcc $USEPREV --defaultPseudoRatio $DEFP --pseudo_ratio $PSR --usingDoubleDecrease $DD --num_segments 3 --gd 20 --lr $LR --lr_steps 180 230 --pre_ratio $PRERATIO --epochs $EPOCHS -b $BATCH -j 8 --dropout 0.8 --snapshot_pref $VER --form_w $FW --main_w $MW --gpu $GPU --wt $WT --flow_pref $FLOWPREF > $VER.txt &
# VER="3.3_u2h_04-08_10w_lr2_noweight_1ratio_correctw_3Dec_0.1defaultp_250epoch_1skip_save180200"
# SOURCE="ucf101_flow_test_split_1"
# TARGET="hmdb51_flow_test_split_1"
# MODE="Flow"
# SMODE="flow"
# FW=0.4
# MW=-0.8
# LR=0.002
# GPU=2
# WT=1
# BATCH=48
# EPOCHS=250
# PRERATIO=0.2
# FLOWPREF="flow_"
# PSR=1
# DD="True"
# TD="True"
# USEPREV="False"
# DEFP=0.1
# SKIP=1
# MP=0.5
# UT1="False"
# echo "${VER}_${SMODE}"
# nohup python main_spcan_ratio_2Dec_prev_save.py hmdb51-10 $MODE datalist/$SOURCE.txt datalist/$TARGET.txt --usingTriDec $TD --max_pseudo $MP --useT1Only $UT1 --arch BNInception --skip $SKIP --usePrevAcc $USEPREV --defaultPseudoRatio $DEFP --pseudo_ratio $PSR --usingDoubleDecrease $DD --num_segments 3 --gd 20 --lr $LR --lr_steps 180 230 --pre_ratio $PRERATIO --epochs $EPOCHS -b $BATCH -j 8 --dropout 0.8 --snapshot_pref $VER --form_w $FW --main_w $MW --gpu $GPU --wt $WT --flow_pref $FLOWPREF > $VER.txt &
